package br.com.fiap.xcave.global.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;
import java.util.Date;

@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "mercado")
@Data
public class Mercado {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @NotBlank(message = "O nome é obrigatório. Digite um nome.")
    @DynamoDBAttribute
    private String name;

    @Email
    @DynamoDBAttribute
    private String email;

    @Size(min = 8, message = "A senha deve ter pelo menos 8 caracteres")
    @DynamoDBAttribute
    private String password;

    @DynamoDBAttribute
    private String role = "admin";

    @DynamoDBAttribute
    private String address;

    @DynamoDBAttribute
    private String number;

    @DynamoDBAttribute
    private String city;

    @DynamoDBAttribute
    private String state;

    @Size(min = 8, message = "O CEP deve ter pelo menos 8 caracteres")
    @DynamoDBAttribute
    private String zipcode;

    @DynamoDBAttribute
    private boolean donating = true;

    @DynamoDBAttribute
    private String picture;

    @DynamoDBAutoGeneratedTimestamp
    @DynamoDBAttribute
    private Date lastUpdated;

}